---
- name: "install dependencies"
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - python
    - python-pip
    - openssh-client
  tags:
    - ansible

- name: "install ansible"
  pip:
    name: "ansible"
    state: present
    version: "{{ ansible_version }}"
  tags:
    - ansible
