---
- name: "install dependencies"
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - python
    - python-pip
    - openssh-client
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded
  tags:
    - ansible

- name: "install ansible"
  pip:
    name: "ansible"
    state: present
    version: "{{ ansible_version }}"
  retries: "{{ remote_package_retries }}"
  register: pip_result
  until: pip_result is succeeded
  tags:
    - ansible
